### ISSUE TITLE
功能好像没有写完

### ISSUE THREAD

**Issue by whale2002** [Elylicery/Vue-Shop-Management-System#1]
## 功能好像没有做完

**Comment by Elylicery** [comment]
嗯嗯，就是跟着视频做的，视频里写的我就写了，视频里没写的我就没写（有的增删改是重复的就没有写了



在 2021-09-06 21:56:04，"coder-chin" ***@***.***> 写道：

功能好像没有做完

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
